### ISSUE TITLE
Use of PathBuf variable in Quotes Breaks in 1.9.6

### ISSUE THREAD

**Issue by catcatmu** [rust-shell-script/rust_cmd_lib#75]
PathBuf variables, when within quotes works in 1.9.5, but returns an error in 1.9.6:

### Build Log:
```
error[E0277]: `PathBuf` doesn't implement `std::fmt::Display`
 --> src/main.rs:3:13
  |
3 |       let _ = cmd_lib::run_cmd! {
  |  _____________^
4 | |         echo "$path";
5 | |         echo "$path";
6 | |     };
  | |_____^ `PathBuf` cannot be formatted with the default formatter; call `.display()` on it
  |
  = help: the trait `std::fmt::Display` is not implemented for `PathBuf`
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
  = note: call `.display()` or `.to_string_lossy()` to safely print paths, as they may contain non-Unicode data
  = note: this error originates in the macro `$crate::__export::format_args` which comes from the expansion of the macro `cmd_lib::run_cmd` (in Nightly builds, run with -Z macro-backtrace for more info)
```

#### main.rs
```
fn main() {
    let path = std::path::PathBuf::from("example.txt");
    let _ = cmd_lib::run_cmd! {
        echo "$path";
        echo "$path";
    };
}
```

#### [Working] Cargo.toml (v1.9.5)
```
[package]
name = "check-path"
version = "0.1.0"
edition = "2024"

[dependencies]
cmd_lib = "=1.9.5"
cmd_lib_macros = "=1.9.5"
```

#### [Not Working] Cargo.toml (v1.9.6)
```
[package]
name = "check-path"
version = "0.1.0"
edition = "2024"

[dependencies]
cmd_lib = "=1.9.6"
cmd_lib_macros = "=1.9.6"
```
